services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: blog_api
    command: uv run uvicorn --factory main:application_factory --workers 2 --host 0.0.0.0 --port 8001 --proxy-headers --forwarded-allow-ips='*'
    ports:
      - "8001:8001"
    volumes:
      - ./web/:/usr/src/web/
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: blog_redis
    volumes:
      - redis_data:/data

  postgres_db:
    image: postgres:17-alpine
    container_name: blog_pgsql_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  redis_data:
    name: blog_redis
  postgres_data:
    name: blog_postgres